#!/bin/bash

#PBS -l nodes=1:ppn=10
#PBS -l walltime=01:30:00


#parse config.json for input parameters 

t1=$(jq -r .t1 config.json)
mask=$(jq -r .mask config.json)


echo "t1: "${t1}
echo "mask: "${mask}

 ( [ -z "${mask}" ]  || [  "${mask}" == "null" ] ) || { mask_opt="  ${mask} "; }

outputdir_0=${PWD}"/outputdir"
outputdir_1=${PWD}"/segmentation"

nthreads=10

template_dir='./data/PTBP/'
singularity exec -e docker://brainlife/ants:2.2.0-1bc bash antsCorticalThicknessSegmentation.sh ${t1} ${template_dir} ${nthreads} ${outputdir_0} ${mask_opt}

# save outputfile 

mkdir -p ${outputdir_1}

cp ${outputdir_0}'/BrainSegmentation.nii.gz'	${outputdir_1}'/segmentation.nii.gz'
cp './data/label.json' ${outputdir_1}

